apiVersion: v1
kind: Service
metadata:
  name: reddit-clone-app-service
  labels:
    app: reddit-clone-app 
spec:
  selector:
    app: reddit-clone-app

  ports:
    - port: 80
      targetPort: 3000

  type: LoadBalancer
